### ISSUE TITLE
jaegertracing/all-in-one container drains memory to the point the hosting system crashes 

### ISSUE THREAD

**Issue by ghevge** [hansehe/jaeger-all-in-one#13]
I've set up recently a system and added  jaegertracing/all-in-one container too. 
Initially I've noticed that my hosting system which is a dual CPU Xeon 2630 V2 with 64GB of RAM was dying after 2-3 hours of intensive load. I thought that my app could be at fault, but after investigating a bit I noticed that the problem is actually   jaegertracing/all-in-one container container which is slowly consuming all the system available RAM memory until the system crashes.
It looks like a memory leak to me.
The only way to stabilize my system was to remove the  jaegertracing/all-in-one container

My system containers are all running on a docker instance.

docker-compose section for jaegertracing looks like below. I haven't defined any memory limits on this container, so I cannot tell you if that trick would have reduce the leak or not.

```
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "16686:16686"
      - "14268"
      - "14250"
    networks:
      mw-network:
        aliases:
          - jaeger-all-in-one
```
